### 
GET http://localhost:3000

### All Pokemons
GET http://localhost:3000/api/v2/pokemon

### Get a Pokemon by ID
GET http://localhost:3000/api/v2/pokemon/300

### Create a Pokemon
POST http://localhost:3000/api/v2/pokemon
Content-Type: application/json

{
  "no": 6,
  "name": "Charmander"
}

### Update a Pokemon
PATCH http://localhost:3000/api/v2/pokemon/685cc8e53e58169bd5726923
Content-Type: application/json

{
  "no": 2,
  "name": "Charmeleonsiuuu"
}

### Delete a Pokemon
DELETE http://localhost:3000/api/v2/pokemon/685cccd9e2cd781ea5082e27

### Seed Pokemons
GET http://localhost:3000/api/v2/seed